- src/control/LayerManager.ts
getAttribute would return null if the attribute was not set, offset returns a number and also bases off of actual dimensions
> use offsetWidth and offsetHeight instead of getAttribute

- src/constants.ts
- src/control/LayerManager.ts
- src/control/MainController.ts
a bug encountered in REP where dimensions were 0 and a offset was added nonetheless
> avoid negative dimensions

- src/layers/base/HTMLLayer.ts
- test/html-layer.test.ts
z-index is set as attribute on HTML layer, but needs to be set as CSS property
> fix order not working for HTMLLayer

- src/layers/base/PixiLayer.ts
Simple setting for Pixi that allows to extract the content of a layer as a picture (using https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toDataURL).
Note that pictures have to be extracted from individual layers, and composed back together if needed. I haven't found a way to directly extract a single picture out of the entire intersection component (but I admit I haven't tried too hard)
> Allow to generate images from PixiLayers

- test/reference-system.test.ts
- tsconfig.json
Some tests were commented out due to an import issue with the Vector2 library in Jest.
Adding esModuleInterop: true to tsconfig lets us import the Vector2 in the Jest tests.
I needed to fix this issue in another unrelated PR, but made it it's own PR for clarity.
There remains three commented tests that needs to be updated. Feel free to hijack this PR or create a new PR to fix those tests as well. Maybe @HavardNJ could have a look, since it's seems he created the tests?
> fix vector2 issue in test

- .storybook/src/complete-example/intersection.stories.ts
- package.json
- src/constants.ts
- src/control/IntersectionReferenceSystem.ts
- src/datautils/wellboreItemShapeGenerator.ts
- src/interfaces.ts
- src/layers/CasingLayer.ts
- src/layers/CementLayer.ts
- src/layers/HoleSizeLayer.ts
- src/layers/WellboreBaseComponentLayer.ts
- src/utils/vectorUtils.ts
- test/vectorUtils.test.ts
- tsconfig.json
- Simplify createNormal and offsetPoints
- Get normals from curve-interpolator
- Add esModuleInterop to tsconfig.json to load Vector2 in Jest tests
- Cache curtain path
- Optimized path generator for hole, casing, and cement
- Simplify shoe render
- Optimize drawing of cement by using pixi.js SimpleRope. This also fixes the texure for cement so it streches/warps along the cement path.
- Optimize drawing of hole and casing by dropping the mask. Create textures of correct width so mask is redundant.
- Remove unneeded interpolation from createOffsetCoords()
- Remove unneeded actualPoints()
- Fix memory leak where Graphics object was not deleted after use. (This is still not optimal. The layers should update the graphics objects and not create new on every frame. Creating new graphics objects …
> fix well layers rendering artifacts

- .storybook/addons.js
- .storybook/config.js
- .storybook/main.js
- .storybook/webpack.config.js
- package-lock.json
- package.json
Update storybook to fix Dependabot alert about vulnerability in prismjs 
- Update storybook configuration to new "0-config" setup
- Update storybook-dark-mode
- Add @storybook/addon-docs to get @storybook/addon-storysource working
@storybook/addon-storysource wouldn't find the source files and the only way I found to get it working was adding @storybook/addon-docs
Closes #356
> update storybook to 6.0.21

- src/layers/GeomodelLayer.ts
- src/layers/GeomodelLayerV2.ts
- Render GeoModelLayer lines as lines and not triangle strip.
Fixes #359
Before:
After:
> fix: geomodellayer lines distort when increasing zFactor

- src/interfaces.ts
casingId and casingIds has to be optional until the deprecated casingId is removed in next major release
> fix: casingId and casingIds has to be optional 

- src/control/IntersectionReferenceSystem.ts
- src/interfaces.ts
- test/reference-system.test.ts
This will let the IntersectionReferenceSystem work with position log in both direction (top to bottom and bottom to top). 
The changes touches the MD to displacement calculations and the reverse calculation.
And we have added the possibility to provide a trajectoryAngleStart so both ends of the poslog can get a preset angel.
The changes to IntersectionReferenceSystem.startVector should be reviewed closely by the Videx team as the REP application is using getExtendedTrajectory() that depends on this vector.
> feat: allow displacement calculated from bottom

- src/datautils/surfacedata.ts
- src/layers/GeomodelLabelsLayer.ts
@tormy pointed out that id was used instead of label for GeomodelLabelsLayer drawLineLabel() and drawAreaLabel(). drawAreaLabel() was already fixed though in recent commit.
> fix: print SurfaceLine label, not id

- src/layers/CalloutCanvasLayer.ts
Updating data on CalloutCanvasLayer after panning did not result in update to screen
- Always clear `this.callouts` on new data
- Don't keep isPanning state between renders
> render CalloutCanvasLayer on data update

- src/layers/CalloutCanvasLayer.ts
With displacement calculated from bottom well path goes by default left to right (opposite of standard)
Closes #389
> fix: position callout with displacement calculated from bottom

- src/layers/CasingLayer.ts
- src/layers/CompletionLayer.ts
- src/layers/HoleSizeLayer.ts
- src/layers/WellboreBaseComponentLayer.ts
- src/layers/base/PixiLayer.ts
Browser gave a warning about too many WebGL contexts opened when creating the component a few times.
It's uncertain wether the WEBGL_lose_context trick fixes or just hides the issue, but testing to recreate the layers several hundred times did not reveal any memory leak.
> Fix onUnmount on PixiLayers

- .storybook/src/utils/elements.ts
- src/control/LayerManager.ts
- src/control/MainController.ts
- src/control/overlay.ts
- src/layers/CasingLayer.ts
- src/layers/CementLayer.ts
- src/layers/HoleSizeLayer.ts
- src/layers/base/PixiLayer.ts
- fix bug in PixiLayer onUnmount
- change class name in createLayerContainer, class name was also used in LayerManager
- implement destroy method on Controller to remove overlay and layers from DOM, unmount layers and unset references
Destroy is implemented to help applications safely clean up after use.
> feat: destroy method on Controller

- src/layers/CalloutCanvasLayer.ts
- test/callout-canvas-layer.test.ts
Fixes error when setting data before reference system on CalloutCanvasLayer.
I think we have some similar bugs in the Pixi.js layers. I will look at that and make similar fixes and tests if so.
> fix: use before assign of reference system

- __mocks__/pixi.js.ts
- package.json
- src/layers/CasingLayer.ts
- src/layers/CementLayer.ts
- src/layers/HoleSizeLayer.ts
- test/callout-canvas-layer.test.ts
- test/casing-layer.test.ts
- test/cement-layer.test.ts
- test/hole-layer.test.ts
- test/test-helpers.ts
- add tests
- mock parts of Pixi.js for tests
- check for referenceSystem before render
I have a coming PR depending on this one that will cleanup the pixi layers some more
> fix: use referencesystem before assign in WellboreBaseComponentLayers

- .storybook/src/complete-example/intersection.stories.ts
- src/layers/CasingLayer.ts
- src/layers/CementLayer.ts
- src/layers/GeomodelLayerV2.ts
- src/layers/HoleSizeLayer.ts
- src/layers/WellboreBaseComponentLayer.ts
- src/layers/base/PixiLayer.ts
- cleanup render method on WellboreBaseComponentLayers
Make WellboreBaseComponentLayer and it's render method abstract to allow for missing implementation
Remove the redundant onUpdate methods on WellboreBaseComponentLayers
- render GeomodelLayerV2 on first rescale
- cleanup GeomodelLayerV2
- fix issue with redefined getters
avoid redeclaring "options" on HoleSizeLayer just to change type signature. It is not allowed to redeclare and change a gettter to an object property
> refactor: clean up pixilayers

- src/constants.ts
- src/interfaces.ts
- src/layers/CasingLayer.ts
- src/layers/CementLayer.ts
- src/layers/HoleSizeLayer.ts
- src/layers/WellboreBaseComponentLayer.ts
- Remove unused options on HoleSizeLayer, CasingLayer, CementLayer and WellboreBaseComponentLayer
- Remove rendering of closed end on HoleSizeLayer
- Improve texture cache and optimize texture creation for HoleSizeLayer, CasingLayer, CementLayer
- small code improvements
Closes https://github.com/equinor/wellx-designer/issues/62 https://github.com/equinor/esv-intersection/issues/296
> improve wellborelayers textures

- src/control/IntersectionReferenceSystem.ts
When using IntersectionReferenceSystem with calculateDisplacementFromBottom project() method calculates distance from bottom to input MD wrong and throws of the intersection coordinates returned.
> fix bug in IntersectionReferenceSystem::project 

- src/interfaces.ts
- src/layers/base/PixiLayer.ts
- Let Pixi Application options be configurable
This lets the users of this library configure Pixi.js Application for pixi layers if default setting don't cover their use case.
> feat: Let Pixi Application options be configurable

- package-lock.json
- package.json
- src/interfaces.ts
- src/layers/base/PixiLayer.ts
- tsconfig.json
- upgrade pixi.js to 6.4.2
- tsconfig change, set skipLibCheck to true. Stop type checking of dependencies. No need for this library to typecheck dependencies.
- Update to changes in PIXI.js types
> chore: upgrade to PIXI.js 6 4.2

- src/layers/base/PixiLayer.ts
Use preferred `backgroundAlpha` property of IRendererOptions instead.
https://pixijs.download/dev/docs/PIXI.AbstractRenderer.html#backgroundAlpha
> Change deprecated `transparent` property to `backgroundAlpha`

- src/control/LayerManager.ts
- src/layers/CalloutCanvasLayer.ts
- src/layers/CasingAndCementLayer.ts
- src/layers/CasingLayer.ts
- src/layers/CementLayer.ts
- src/layers/CompletionLayer.ts
- src/layers/GeomodelCanvasLayer.ts
- src/layers/GeomodelLabelsLayer.ts
- src/layers/GeomodelLayerV2.ts
- src/layers/GridLayer.ts
- src/layers/HoleSizeLayer.ts
- src/layers/ImageCanvasLayer.ts
- src/layers/SeismicCanvasLayer.ts
- src/layers/WellborePathLayer.ts
- src/layers/base/HTMLLayer.ts
- src/layers/base/Layer.ts
- src/layers/base/PixiLayer.ts
- test/layer.test.ts
Part of the esv-improvement-efforts is to merge all pixi layers into one. With that comes the need to update how visibility can toggle to show different parts of the well.
This PR lets users have a internal layer options so that CasingAndCement can show/hide casings and cements seperately.
> feat: update pixi visibility toggle

- src/constants.ts
- src/layers/ImageComponentLayer.ts
- we are drawing textures from top down along the wellbore and therefore have to flip and mirror the texture
- adjust hole outline and screen outline thickness
> fix: flip wellbore textures

- .storybook/src/complete-example/intersection.stories.ts
- .storybook/src/features/schematic-layer.stories.ts
- src/control/LayerManager.ts
- src/datautils/schematicShapeGenerator.ts
- src/layers/CustomDisplayObjects/ComplexRopeGeometry.ts
- src/layers/SchematicLayer.ts
- src/layers/schematicInterfaces.ts
- test/schematicShapeGenerator.test.ts
- test/test-helpers.ts
-Remove `casingId` from casings. Items referencing that id should rather use the `id` of the casing instead.
-Rename `casingIds` to `referenceIds` for cement related items, as tubing/screen can be cemented in some cases.
Related data is merged from: https://github.com/equinor/esv-intersection-data/pull/11
Refactoring related to PAndA items:
https://github.com/equinor/esv-intersection/issues/461
https://github.com/equinor/esv-intersection/issues/459
https://github.com/equinor/esv-intersection/issues/482
> Use referenceIds instead of casingIds

- src/layers/SchematicLayer.ts
Fix in this commit https://github.com/equinor/esv-intersection/commit/18ffebbceea57432ac9108eefdc294f9dd2c54d5 seems to have been lost
> fix: regression bug on symbol textures

- src/datautils/schematicShapeGenerator.ts
- src/layers/SchematicLayer.ts
- test/schematicShapeGenerator.test.ts
The dashed outline should always be on the upside of the wellbore (facing the surface). Also fixes the case where an interval wasn't strictly overlapping the casing.
Related issue: https://github.com/equinor/wellx-designer/issues/715
> fix: Casing window intervals and outline

- package-lock.json
- package.json
- src/layers/SchematicLayer.ts
- src/layers/base/PixiLayer.ts
- src/vendor/pixi-dashed-line/index.ts
- vite.config.ts
* update to pixi v7
* vendor pixi-dashed-line package
pixi-dashed-line depends on pixi v.6 and causes peerDependency conflict when upgrading to PixiJS v7
> chore: upgrade pixi.js to v7

- src/datautils/schematicShapeGenerator.ts
- src/layers/SchematicLayer.ts
Remove non-WebGL fallback code in SchematicLayer since Chrome/Edge's Swift renderer (software CPU renderer) is fast enough and produces perfect results.
Issue: https://github.com/equinor/esv-intersection/issues/535
> Remove canvas fallback

- package-lock.json
- package.json
- src/control/ExtendedCurveInterpolator.ts
- src/control/IntersectionReferenceSystem.ts
- src/layers/GeomodelLabelsLayer.ts
- src/utils/arc-length.ts
Can be rebased after https://github.com/equinor/esv-intersection/pull/545
Minor release of `curve-interpolator` has breaking changes. I went through the changeset of `3.0.1 => 3.1.1` and the following seems like the correct changes:
`lookup => getIntersects`
lookup docs: https://github.com/kjerandp/curve-interpolator/compare/3.0.1..3.1.1#diff-425c2d7c81b652a656e544922478f4cd278885e96fa05b38597992953cbefb0dL168
getIntersects doc: https://github.com/kjerandp/curve-interpolator/compare/3.0.1..3.1.1#diff-425c2d7c81b652a656e544922478f4cd278885e96fa05b38597992953cbefb0dR449-R462
`lookupPositions => getIntersectsAsPositions`
Implementation changed, docs stayed the same: https://github.com/kjerandp/curve-interpolator/compare/3.0.1..3.1.1#diff-425c2d7c81b652a656e544922478f4cd278885e96fa05b385979929 …
> chore(dependencies): Upgrade dependencies

- package-lock.json
- package.json
- src/layers/CalloutCanvasLayer.ts
Related to this task: [#5176](https://github.com/equinor/mad-project-rep/issues/5176)
> Added configurable background to callout canvas layer
