equinor/esv-intersection

- .github/workflows/unittests.yml
- .gitignore
- package-lock.json
- package.json
Resolves #2
Removed `package-lock.json` from gitignore and added the file itself in order to be able to run the ci pipeline
> Ci pipeline unit tests

- .storybook/config.js
- .storybook/src/index.stories.ts
- .storybook/webpack.config.js
- package-lock.json
- package.json
> setup storybook

- .prettierrc.yaml
- .storybook/src/grid-layer.stories.ts
createEventObj was missing required parameter elm
Also enable semicolons enforcing for prettier
> bugfix: Add element to createEventObj

- .dockerignore
- nginx.conf
- radixconfig.yaml
- storybook.Dockerfile
> feature storybook deployed

- src/layers/SVGLayer.ts
- test/index.test.ts
> forgot to remove element reference

- README.md
> Added links to ESV, Storybook and NPM package

- .github/workflows/npmpublish.yml
- package-lock.json
- package.json
automatic deployment happens when a release has been set up on GitHub
> setup automatic package deployment

- .storybook/src/intersection.stories.ts
- .storybook/src/layers/callout-with-zoom.stories.ts
- .storybook/src/layers/index.stories.ts
- src/layers/CalloutCanvasLayer.ts
- src/layers/CanvasLayer.ts
- src/utils/text.ts
- test/callout.test.ts
> added some initial text placement logic

- .storybook/src/intersection.stories.ts
- src/control/LayerManager.ts
- src/control/MainManager.ts
- src/control/ScaleManager.ts
- src/control/index.ts
- src/interfaces.ts
- src/layers/CalloutCanvasLayer.ts
- src/layers/GeomodelLayer.ts
- src/layers/ImageCanvasLayer.ts
> created layer manager

- package-lock.json
- package.json
preparing for a release with associated npm publish
> Bump version to 0.2.0-alpha

- src/interfaces.ts
- src/layers/CasingLayer.ts
- src/layers/GeomodelCanvasLayer.ts
- src/layers/GeomodelLabelsLayer.ts
- src/layers/GeomodelLayer.ts
- src/layers/GridLayer.ts
- src/layers/HoleSizeLayer.ts
- src/layers/Layer.ts
- src/layers/SVGLayer.ts
- src/layers/WellboreBaseComponentLayer.ts
- src/layers/WellborePathLayer.ts
- test/index.test.ts
> functioning default for layers, also added setData and clearData

- src/control/IntersectionReferenceSystem.ts
- src/control/MainController.ts
- src/control/interfaces.ts
- src/interfaces.ts
> use offset when projecting, getter/setter

- .storybook/src/intersection.stories.ts
- src/components/axis.ts
- src/control/LayerManager.ts
- src/control/MainController.ts
> added the ability to toggle axis

- README.md
- src/control/LayerManager.ts
- src/control/MainController.ts
> added getting started section, added comments to methods

- src/layers/base/HTMLLayer.ts
- test/controller.test.ts
- test/html-layer.test.ts
fixed some bugs that tests found
> More tests

- rollup.config.js
> Added peer dependencies to external for rollup

- .eslintrc.json
- .storybook/src/layers/html/highlight.stories.ts
- src/control/IntersectionReferenceSystem.ts
- test/reference-system.test.ts
also added a gridlayer to see the ticks better
fixes #220
> added offset according to first point in poslog

- src/layers/WellboreBaseComponentLayer.ts
> Clear old data when updated

- src/control/overlay.ts
> Casting Element to an allowable type

- package-lock.json
Address a vulnerability that was reported by npm
> Updated version of yargs-parser

- src/interfaces.ts
- src/layers/CalloutCanvasLayer.ts
> Use options/defaults instead of hard coded values in callout layer

- CHANGELOG.md
> created changelog with previous releases

- package-lock.json
> resolve vulnerability

- CHANGELOG.md
- package-lock.json
- package.json
> bumped version to 0.9.5-alpha and update changelog

- src/datautils/wellboreItemShapeGenerator.ts
- test/wellboreItemShapeGenerator.test.ts
The isBetween function did not return true when either top or bottom of cement was equal to top or bottom of hole. (Check was < or >, needs to be <= and >=)
> fix overlaps check

- .gitignore
- src/layers/CementLayer.ts
- src/layers/CompletionLayer.ts
- src/utils/vectorUtils.ts
- test/reference-system.test.ts
Supersedes PR #330 
This is a first small step in using Vector2 instead of the home made vector algebra for anything that has to be displayed along the wellbore (hole, cement, casing, etc). We have just started using Vector2 in vectorUtils.ts and we are just reproducing the previous behavior. Further refactoring and optimization will come in later PRs
> Use Vector2 for well-related visualizations - Part 1

- .github/workflows/github-pages.yml
I am not sure I can try workflows from a branch different from master, I may consider merging this without a review... sorry!
> Automatic build and deploy storybook and docs

- .storybook/src/features/geomodel-layer.stories.ts
Add story for GeomodelCanvasLayer as was not used anywhere.
Please review also the help text for te story. I don't know if this is fully correct?
"High level interface for creating and displaying geo model (aka surfaces). This layer is made using plain HTML canvas. GeomodelLayer is preferred for rendering geo models if your browser supports WebGL."
> Add storybook story for GeomodelCanvasLayer

- .storybook/src/complete-example/intersection.stories.ts
- src/layers/CasingLayer.ts
- src/layers/CompletionLayer.ts
- src/layers/GeomodelLayerV2.ts
- src/layers/HoleSizeLayer.ts
- src/layers/ImageCanvasLayer.ts
- src/layers/WellboreBaseComponentLayer.ts
- src/layers/base/PixiLayer.ts
- Fix flipping of x axis when xbounds are inverse.
- Add storybook story for flipped x axis
> flip X on several layers

- .storybook/src/features/highlight.stories.ts
> Fix possible bug wellborepath layer

- src/control/IntersectionReferenceSystem.ts
- src/curveinterpolator.d.ts
- src/datautils/trajectory.ts
- Remove obsolete src/curveinterpolator.d.ts
- Update use of CurveInterpolator to addhere to type definitions
> Use typescript types from curve-interpolator

- .storybook/src/complete-example/intersection.stories.ts
- src/layers/base/PixiLayer.ts
- remove obsolete arguments to constructors
- remove unused setTransform method on PixiLayer
> cleanup code

- src/control/ZoomPanHandler.ts
- src/layers/CasingLayer.ts
- src/layers/CementLayer.ts
- src/layers/HoleSizeLayer.ts
- src/layers/WellboreBaseComponentLayer.ts
- src/layers/base/Layer.ts
- src/utils/vectorUtils.ts
Alternative implementation of zFactor fix. For other implementation see #377
> compensate for zFactor in WellboreBaseComponentLayers

- CHANGELOG.md
- src/layers/base/Layer.ts
- test/layer.test.ts
This will add consistency when setting data
> should use setData function when data is set upon creation

- src/control/LayerManager.ts
- src/control/index.ts
Some or all of these interfaces are needed from the outside
> Export interfaces in control/interfaces.ts

- __mocks__/pixi.js.ts
- src/layers/CasingLayer.ts
- src/layers/CementLayer.ts
- src/layers/CompletionLayer.ts
- src/layers/GeomodelLayerV2.ts
- src/layers/HoleSizeLayer.ts
- src/layers/WellboreBaseComponentLayer.ts
- src/layers/base/PixiLayer.ts
Create custom pixi application for handling pixi render to avoid PIXI.Application's requestAnimationFrame render loop
Only render Pixi layers on input changes and user interactions
> feat: stop PIXI requestAnimationFrame render loop

- src/interfaces.ts
- src/layers/CasingLayer.ts
Let's the implementer override default shoe size.
Issue: https://github.com/equinor/wellx-designer/issues/653
> feat: Add customizable casing shoe size

- .eslintrc.json
- package.json
- src/control/ExtendedCurveInterpolator.ts
- src/control/IntersectionReferenceSystem.ts
- src/datautils/findsample.ts
- src/datautils/seismicimage.ts
- src/datautils/surfacedata.ts
- src/datautils/wellboreItemShapeGenerator.ts
- src/layers/CalloutCanvasLayer.ts
- src/layers/GeomodelLabelsLayer.ts
- src/layers/WellboreBaseComponentLayer.ts
- src/layers/WellborePathLayer.ts
- src/layers/base/CanvasLayer.ts
- src/utils/arc-length.ts
- src/utils/binary-search.ts
- test/callout-canvas-layer.test.ts
- test/callout.test.ts
- test/casing-layer.test.ts
- test/cement-layer.test.ts
- test/hole-layer.test.ts
- test/layer.test.ts
- test/reference-system.test.ts
- test/svg-layer.test.ts
- test/test-helpers.ts
- test/utils/color.test.ts
- test/vectorUtils.test.ts
* Stop ignoring eslint rule no-explicit-any
* Stop ignoring eslint rule no-unused-vars
* Stop ignoring eslint rule no-magic-numbers
* Start linting tests files
>  increase linting

- .storybook/src/complete-example/intersection.stories.ts
- .storybook/src/features/casing-layer.stories.ts
- .storybook/src/features/cement-layer.stories.ts
- .storybook/src/features/completion-layer.stories.ts
- .storybook/src/features/geomodel-layer.stories.ts
- .storybook/src/features/holesize-layer.stories.ts
- src/control/LayerManager.ts
- src/layers/CasingLayer.ts
- src/layers/CementLayer.ts
- src/layers/CompletionLayer.ts
- src/layers/GeomodelCanvasLayer.ts
- src/layers/GeomodelLayerV2.ts
- src/layers/HoleSizeLayer.ts
- src/layers/WellboreBaseComponentLayer.ts
- src/layers/base/PixiLayer.ts
- test/casing-layer.test.ts
- test/cement-layer.test.ts
- test/hole-layer.test.ts
This PR is a step towards simplifying and getting better performance in esv-intersection.
Previously we created a absolute positioned HTML element and created a PIXI Application inside the component; Now we pass in a PIXI Application in the constructor of the Layer class, and achieve the layering effect by using a PIXI Display Object.
```
// PixiLayer.ts
constructor(ctx: Application | PixiRenderApplication, id?: string, options?: LayerOptions) {
super(id, options);
this._ctx = ctx;
this._container = new Container();
this._ctx.stage.addChild(this._container);
}
```
> feat: shared pixi application context

- .storybook/src/complete-example/intersection.stories.ts
- .storybook/src/features/casing-and-cement.stories.ts
- .storybook/src/features/casingCement.stories.ts
- .storybook/src/features/index.stories.ts
- package-lock.json
- package.json
- src/layers/CasingAndCementLayer.ts
- src/layers/CementLayer.ts
- src/layers/index.ts
Combined casing and cement into one layer in order to get the rendering order correct. The individual cement and casings needs to render in ordered pairs to get the visual overflows correct.
The visibility toggle for the layer hides both cement and casings at the moment.
Issue: https://github.com/equinor/wellx-designer/issues/125
> fix: Casing shoe now renders above cement

- src/datautils/wellboreItemShapeGenerator.ts
- src/layers/CasingAndCementLayer.ts
- src/layers/CementLayer.ts
- src/layers/CustomDisplayObjects/ComplexRope.ts
- src/layers/CustomDisplayObjects/ComplexRopeGeometry.ts
- test/cement-layer.test.ts
- Render cemnet with ComplexRope and ComplexRopeGeometry
This will improve performance and visuals of cement
> feat: Render cement with new ComplexRope geometry

- src/constants.ts
- src/layers/CasingAndCementLayer.ts
- src/layers/CompletionLayer.ts
- src/layers/CustomDisplayObjects/ComplexRope.ts
- src/layers/CustomDisplayObjects/ComplexRopeGeometry.ts
- src/layers/CustomDisplayObjects/FixedWidthSimpleRope.ts
- src/layers/HoleSizeLayer.ts
- Implement scaling for completion layer
- Improve cement and screen textures
- Create hole texture based on max diameter of holes
> fix: improve scaling and textures

- src/datautils/wellboreItemShapeGenerator.ts
- src/layers/CasingAndCementLayer.ts
- src/layers/CementLayer.ts
- src/layers/CompletionLayer.ts
- src/layers/CustomDisplayObjects/FixedWidthSimpleRope.ts
- src/layers/HoleSizeLayer.ts
- src/layers/WellboreBaseComponentLayer.ts
- test/cement-layer.test.ts
- draw hole outline outside hole diameter
- make sure CementLayer follows implementation of CasingAndCementLayer
- draw textures all the way to the edge
- rename StaticWidthSimpleRope to FixedWidthSimpleRope
- adjust cement in hole
- simplify tubing texture
> fix: pixi layers fixes

- src/control/LayerManager.ts
- src/control/MainController.ts
- src/control/interfaces.ts
Simplify things by making LayerManager and Controller non generic.
> refactor: LayerManager and Controller non generic

- .storybook/src/complete-example/intersection.stories.ts
- .storybook/src/data.ts
- .storybook/src/features/schematic-layer.stories.ts
- .vscode/settings.json
- src/datautils/wellboreItemShapeGenerator.ts
- src/interfaces.ts
- src/layers/CasingAndCementLayer.ts
- src/layers/SchematicLayer.ts
Cement squeeze in esv-intersection#482
Render cement squeeze. (Might be same as normal casing cement but with different color)
> feat: render cement squeeze

- .storybook/src/features/schematic-layer.stories.ts
- src/datautils/wellboreItemShapeGenerator.ts
- src/interfaces.ts
- src/layers/SchematicLayer.ts
Render cement plug in esv-intersection
> feat: cement plug

- .github/workflows/npmpublish-beta.yml
- package.json
Thought is to tag the prerelease with a beta tag on the registry
> Add own action for prereleases

- package-lock.json
- package.json
- src/datautils/schematicShapeGenerator.ts
- src/layers/CustomDisplayObjects/ComplexRope.ts
- src/layers/SchematicLayer.ts
- src/layers/schematicInterfaces.ts
- src/utils/vectorUtils.ts
- test/schematicShapeGenerator.test.ts
- test/test-helpers.ts
- test/vectorUtils.test.ts
Introduces casing windows on the intersection:
Related data change: https://github.com/equinor/esv-intersection-data/pull/12
Issue: https://github.com/equinor/wellx-designer/issues/715
> feat: support casing window string operation

- src/layers/ReferenceLineLayer.ts
Issue: https://github.com/equinor/esv-intersection/issues/163
> fix: Remove negative depth for dashed lines

- .github/workflows/github-pages.yml
- .github/workflows/npmpublish.yml
- README.md
* Build and deploy documentation and storybook to github pages on release
* Build storybook and deploy subdir storybook/master to github pages on each merge to master
* Update documentation
> chore: update github pages deployments and update docs

- src/datautils/schematicShapeGenerator.ts
- src/layers/schematicInterfaces.ts
> fix: perforation height

- .changeset/quick-bags-check.md
- src/layers/GeomodelLayerV2.ts
Closes in Jira: [WBWLS-273](https://drillingandwellsolutions.atlassian.net/jira/software/c/projects/WW/boards/167?modal=detail&selectedIssue=WBWLS-273)
> fix: line data can be empty in QA

- .github/workflows/codeql-analysis.yml
- .github/workflows/github-pages.yml
- .github/workflows/main.yml
- .github/workflows/release.yml
> chore: pin actions to commit
